import { Hono } from "hono";
import { adminRoutes } from "./routes/admin";
import { agentRunRoutes } from "./routes/agentRuns";
import { categoryRoutes } from "./routes/categories";
import { configRoutes } from "./routes/config";
import { conversationRoutes } from "./routes/conversations";
import { eventRoutes } from "./routes/events";
import { experimentRoutes } from "./routes/experiments";
import { goalRoutes } from "./routes/goals";
import { jobRoutes } from "./routes/jobs";
import { proposalRoutes } from "./routes/proposals";
import { rantLinkRoutes } from "./routes/rantLinks";
import { registryRoutes } from "./routes/registry";
import { userRoutes, writeupRoutes } from "./routes/user";

export const app = new Hono();

app.route("/api/admin", adminRoutes);
app.route("/api/config", configRoutes);
app.route("/api/events", eventRoutes);
app.route("/api/conversations", conversationRoutes);
app.route("/api/categories", categoryRoutes);
app.route("/api/rant-links", rantLinkRoutes);
app.route("/api/proposals", proposalRoutes);
app.route("/api/jobs", jobRoutes);
app.route("/api/goals", goalRoutes);
app.route("/api/registry", registryRoutes);
app.route("/api/user", userRoutes);
app.route("/api/writeup", writeupRoutes);
app.route("/api/experiment", experimentRoutes);
app.route("/api/agent-runs", agentRunRoutes);
