import { Hono } from "hono";
import { adminRoutes } from "./routes/admin";
import { agentRunRoutes } from "./routes/agentRuns";
import { anchorRoutes, calendarRoutes } from "./routes/calendar";
import { chatRoutes } from "./routes/chat";
import { configRoutes } from "./routes/config";
import { conversationRoutes } from "./routes/conversations";
import { eventRoutes } from "./routes/events";
import { experimentRoutes } from "./routes/experiments";
import { extractionRoutes } from "./routes/extractions";
import { goalRoutes } from "./routes/goals";
import { jobRoutes } from "./routes/jobs";
import { proposalRoutes } from "./routes/proposals";
import { environmentRoutes, experienceRoutes, habitRoutes } from "./routes/registries";
import { userRoutes, writeupRoutes } from "./routes/user";
import { strikeRoutes, vitalsRoutes } from "./routes/vitals";
import { witnessRoutes } from "./routes/witnesses";
import { reviewRoutes } from "./routes/reviews";
import { outboxRoutes } from "./routes/outbox";
import { l3Routes } from "./routes/l3";
import { shapingRoutes } from "./routes/shaping";

export const app = new Hono();

app.route("/api/admin", adminRoutes);
app.route("/api/config", configRoutes);
app.route("/api/events", eventRoutes);
app.route("/api/conversations", conversationRoutes);
app.route("/api/extractions", extractionRoutes);
app.route("/api/proposals", proposalRoutes);
app.route("/api/jobs", jobRoutes);
app.route("/api/goals", goalRoutes);
app.route("/api/habits", habitRoutes);
app.route("/api/environment", environmentRoutes);
app.route("/api/experiences", experienceRoutes);
app.route("/api/experiments", experimentRoutes);
app.route("/api/chat", chatRoutes);
app.route("/api/calendar", calendarRoutes);
app.route("/api/anchors", anchorRoutes);
app.route("/api/user", userRoutes);
app.route("/api/writeup", writeupRoutes);
app.route("/api/vitals", vitalsRoutes);
app.route("/api/strikes", strikeRoutes);
app.route("/api/witnesses", witnessRoutes);
app.route("/api/reviews", reviewRoutes);
app.route("/api/outbox", outboxRoutes);
app.route("/api/l3", l3Routes);
app.route("/api/shaping", shapingRoutes);
app.route("/api/agent-runs", agentRunRoutes);
